# ===== Nombre del microservicio =====
spring.application.name=ms-sucursales

# ===== Puerto =====
# Cada MS corre en su propio puerto. Sucursales = 8087.
server.port=8087

# ===== Conexión a la base de datos (MySQL en XAMPP) =====
# createDatabaseIfNotExist=true -> si la BD no existe, la crea sola (portabilidad)
spring.datasource.url=jdbc:mysql://localhost:3306/db_perfulandia_logistica?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# ===== JPA / Hibernate =====
# update -> crea/actualiza las tablas según mis entidades (Sucursal, Ruta, Destino)
spring.jpa.hibernate.ddl-auto=update
# muestra el SQL en la consola (para ver qué hace por dentro)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# dialecto de MySQL (OJO: MySQLDialect, NO MySQL8Dialect, ese te dio error antes)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect